import { NavBar } from "@components/NavBar";
import { Providers } from "@components/Provider";
import "@styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Text, Link } from "@chakra-ui/react";
// import { NavBar as NavBarNew } from "@components/NavBar_new";
import { CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CanLNCG4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" />
      </head>
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {/* <NavBarNew />
          <CssBaseline /> */}

          {children}
          <Box
            sx={{
              mt: 10,
              backgroundColor: "#000000",
              width: "100%",
              height: "40px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#ffffff",
            }}
          >
            <Text sx={{ fontSize: 15, width: "100%", textAlign: "center" }}>
              Facilitated by{" "}
              <Link href="https://iitgn.ac.in" target="_blank">
                Indian Institute of Technology Gandhinagar (IITGN)
              </Link>
            </Text>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
